OPRE - Operations Research - Ostschweizer Fachhochschule (OST)

# Facility Location Problem

Das Facility Location Problem (FLP) ist ein klassisches Optimierungsproblem, bei dem es darum geht, den optimalen Standort für Einrichtungen wie Fabriken oder Lagerhäuser zu bestimmen. Ziel ist es, die Gesamtkosten zu minimieren, die durch Transport, Bau und Betrieb entstehen. Dabei werden verschiedene Faktoren wie die Nachfrage der Kunden, die Kosten der Einrichtungen und die Entfernungen berücksichtigt.

#### **Aufgabe**

Ihr Ingenieurbüro bietet Entscheidungsunterstützung für Gemeinden bei der Planung von Feuerwehrdepots, Rettungsdienst-Stützpunkten, Schulhausbauten und anderen standortbezogenen Planungsfragen. Aktuell unterstützen Sie mehrere Gemeinden bei der Frage, an welchen potentiellen Standorten sinnvollerweise Feuerwehrdepots errichtet werden sollen, damit alle gemeldeten Wohneinheiten von einem Depot aus in der kritischen Distanz erreicht werden können. Neben einer Distanzmatrix mit den Entfernungen zwischen Depots und Wohneinheiten (Units) geben die Gemeinden auch an, welches die kritische Distanz einer Wohnung vom Depot sein darf, damit die Wohnung gerade noch als abgedeckt gilt. Die Gemeinden geben zudem die Kosten bekannt, die mit der Eröffnung eines Depots verbunden sind. Sie fordern, dass die Auswahl der Depots so getroffen wird, dass die Kosten zum Errichten der Depots minimal werden. 

Ihnen liegen für verschiedene Gemeinden nachfolgende Problem-Instanzen zur Standortoptimierung von Feuerwehrdepots vor. Sie werden von der Geschäftsleitung beauftragt, für diese Problem-Instanzen möglichst gute und gültige Lösungen zu entwickeln. 

*Tipp*: Es gibt in jedem der Beispiele unterschiedliche Ansätze, die zum Ziel führen. Ggf. kann es sogar sinnvoll sein, eingangs mit unterschiedlichen zu experimentieren.


#### **Daten**

Folgende Problem-Instanzen liegen Ihnen vor: 

| FLP Instanz    | #Depots  | #Units |
| -------------- | -------: | -----: | 
| FLP_D3_U10     | 3	    | 10 	 | 
| FLP_D5_U100    | 5        | 100	 | 
| FLP_D7_U800    | 7	    | 800    | 
| FLP_D12_U2000  | 12	    | 2’000	 | 


#### **Hilfestellung**

Zum Einlesen der Problem-Instanzen wird Ihnen eine Funktion zur Verfügung gestellt, falls Sie diese nicht selbst (oder mit ChatGPT) entwickeln wollen. Sie können die Methode 'read_flp_file' der Datei 'data_import_flp.py' entweder direkt in Ihr Skript kopieren, oder sie wie nachfolgend gezeigt in Ihr Skript importieren. Die Problem-Instanzen legen Sie am besten in ein Unterverzeichnis 'data' ab.


In [1]:
import numpy as np
from flp_reader import read_flp_file  # Funktion für Import der Daten

# Import der Daten
crit_dist, depot_costs, distance_matrix = read_flp_file("data/FLP_D3_U10.flp")

print("Kritische Distanz: ", crit_dist)
print("\nDepotkosten:\n", depot_costs)
print("\nDistanzmatrix:\n", distance_matrix)

Kritische Distanz:  12.5

Depotkosten:
 [14000. 28000. 37000.]

Distanzmatrix:
 [[ 5.4  9.2  0.1  3.9  2.   1.3  2.5  4.5  5.1 16.9]
 [ 5.4  8.8  2.7 11.2  0.4  8.6  5.4  7.2  1.9 12.6]
 [10.2 12.3  4.1  8.9 11.2 11.4  1.2  0.6  2.2 14.2]]
